"""add language

Revision ID: 0cf164c7ff71
Revises: 41a852d14150
Create Date: 2025-02-11 16:22:16.377747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf164c7ff71'
down_revision = '41a852d14150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_file', sa.Column('language', sa.String(), nullable=False, server_default='en'))
    op.create_index(op.f('ix_export_file_symbol_id'), 'export_file', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_export_file_user_id'), 'export_file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_file_user_id'), table_name='export_file')
    op.drop_index(op.f('ix_export_file_symbol_id'), table_name='export_file')
    op.drop_column('export_file', 'language')
    # ### end Alembic commands ###
