"""add export file

Revision ID: 41a852d14150
Revises: 29c64af036e5
Create Date: 2025-02-10 17:04:01.573311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a852d14150'
down_revision = '29c64af036e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('symbol_id', sa.BIGINT(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], name=op.f('fk_export_file_symbol_id_symbol')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_export_file_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_file'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_file_user_id'), table_name='export_file')
    op.drop_index(op.f('ix_export_file_symbol_id'), table_name='export_file')
    op.drop_table('export_file')
    # ### end Alembic commands ###
