"""add column user_id

Revision ID: 4668188b3790
Revises: fb3875e89eff
Create Date: 2025-01-14 16:54:18.594046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4668188b3790'
down_revision = 'fb3875e89eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokyo_stock', sa.Column('user_id', sa.BIGINT(), nullable=False))
    op.create_index(op.f('ix_tokyo_stock_user_id'), 'tokyo_stock', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_tokyo_stock_user_id_user'), 'tokyo_stock', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tokyo_stock_user_id_user'), 'tokyo_stock', type_='foreignkey')
    op.drop_index(op.f('ix_tokyo_stock_user_id'), table_name='tokyo_stock')
    op.drop_column('tokyo_stock', 'user_id')
    # ### end Alembic commands ###
