"""add column tokyo_stock_id

Revision ID: 546e5d1502af
Revises: 4668188b3790
Create Date: 2025-01-14 17:17:41.362187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546e5d1502af'
down_revision = '4668188b3790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar', sa.Column('tokyo_stock_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bar', 'tokyo_stock_id')
    # ### end Alembic commands ###
