"""update name of symbol

Revision ID: 679704b7c321
Revises: 546e5d1502af
Create Date: 2025-01-14 23:32:29.325875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679704b7c321'
down_revision = '546e5d1502af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symbol', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symbol', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
