"""add TokyoStock

Revision ID: 6970afc570cf
Revises: f48a9e8c1ce8
Create Date: 2025-01-12 21:48:45.687610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6970afc570cf'
down_revision = 'f48a9e8c1ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokyo_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokyo_stock'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokyo_stock')
    # ### end Alembic commands ###
