"""update Tick

Revision ID: 89df5aed0082
Revises: 657c6e279315
Create Date: 2024-12-17 01:31:36.119766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89df5aed0082'
down_revision = '657c6e279315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tick', 'datetime_msc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tick', sa.Column('datetime_msc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
