"""change created_at

Revision ID: 9831b6a87ae7
Revises: e1f28ba291ea
Create Date: 2025-01-15 17:25:53.048110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9831b6a87ae7'
down_revision = 'e1f28ba291ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokyo_stock', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokyo_stock', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
