"""add hiragana_name

Revision ID: 9df1bd5f8b2a
Revises: e49c565ee381
Create Date: 2025-02-24 04:04:37.366732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df1bd5f8b2a'
down_revision = 'e49c565ee381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hiragana_name', sa.String(length=255), nullable=True))
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.drop_column('user', 'hiragana_name')
    # ### end Alembic commands ###
