"""init

Revision ID: b0752ebe1a84
Revises: 
Create Date: 2024-12-13 09:01:18.127396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0752ebe1a84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator'))
    )
    op.create_index(op.f('ix_indicator_name'), 'indicator', ['name'], unique=False)
    op.create_table('symbol',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('symbol_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Stock', 'Forex', 'Commodities', 'Indices')", name=op.f('ck_symbol_category_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbol'))
    )
    op.create_index(op.f('ix_symbol_name'), 'symbol', ['name'], unique=True)
    op.create_table('user',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('enabled', 'disabled')", name=op.f('ck_user_state_check')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_user_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('bar',
    sa.Column('from_time', sa.Date(), nullable=False),
    sa.Column('to_time', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('provisional_open', sa.Float(), nullable=True),
    sa.Column('provisional_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('symbol_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], name=op.f('fk_bar_symbol_id_symbol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bar'))
    )
    op.create_table('tick',
    sa.Column('datetime_msc', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('last', sa.Float(), nullable=False),
    sa.Column('volume', sa.INTEGER(), nullable=False),
    sa.Column('symbol_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], name=op.f('fk_tick_symbol_id_symbol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tick'))
    )
    op.create_table('watchlist',
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('sections', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_watchlist_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist'))
    )
    op.create_index(op.f('ix_watchlist_title'), 'watchlist', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_title'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_table('tick')
    op.drop_table('bar')
    op.drop_table('user')
    op.drop_index(op.f('ix_symbol_name'), table_name='symbol')
    op.drop_table('symbol')
    op.drop_index(op.f('ix_indicator_name'), table_name='indicator')
    op.drop_table('indicator')
    # ### end Alembic commands ###
