"""add japanese_name

Revision ID: c87408d11c6a
Revises: 026bd90c7a6d
Create Date: 2025-02-04 08:36:26.959247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87408d11c6a'
down_revision = '026bd90c7a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol', sa.Column('japanese_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbol', 'japanese_name')
    # ### end Alembic commands ###
