"""add file_size

Revision ID: e1f28ba291ea
Revises: 679704b7c321
Create Date: 2025-01-15 16:24:02.781696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f28ba291ea'
down_revision = '679704b7c321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokyo_stock', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokyo_stock', 'file_size')
    # ### end Alembic commands ###
