"""add MA_Line_Point and MA_Lines_Intersection_Point

Revision ID: e49c565ee381
Revises: 6ee859994635
Create Date: 2025-02-18 17:04:33.932243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49c565ee381'
down_revision = '6ee859994635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ma_line_point',
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('bar_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('symbol_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], name=op.f('fk_ma_line_point_symbol_id_symbol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ma_line_point'))
    )
    op.create_index(op.f('ix_ma_line_point_bar_type'), 'ma_line_point', ['bar_type'], unique=False)
    op.create_index(op.f('ix_ma_line_point_symbol_id'), 'ma_line_point', ['symbol_id'], unique=False)
    op.create_table('ma_lines_intersection_point',
    sa.Column('line1_period', sa.Integer(), nullable=False),
    sa.Column('line2_period', sa.Integer(), nullable=False),
    sa.Column('bar_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('symbol_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], name=op.f('fk_ma_lines_intersection_point_symbol_id_symbol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ma_lines_intersection_point'))
    )
    op.create_index(op.f('ix_ma_lines_intersection_point_bar_type'), 'ma_lines_intersection_point', ['bar_type'], unique=False)
    op.create_index(op.f('ix_ma_lines_intersection_point_symbol_id'), 'ma_lines_intersection_point', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ma_lines_intersection_point')
    op.drop_table('ma_line_point')
    # ### end Alembic commands ###
