"""update Tick

Revision ID: fa5a516ddcf2
Revises: 89df5aed0082
Create Date: 2024-12-17 01:32:24.606333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5a516ddcf2'
down_revision = '89df5aed0082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tick', sa.Column('datetime_msc', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tick', 'datetime_msc')
    # ### end Alembic commands ###
